### ISSUE TITLE
[Bug Report] - Infinite Console Error Loop

### ISSUE THREAD

**Issue by joshua-cornett** [codeforpdx/PASS#664]
### Describe the bug:

Throughout the application, an infinite error loop can be observed in the developer console. These errors read: 

```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

Uncaught (in promise) TypeError: codes.forEach is not a function
    at LanguageUtil.getBestMatchFromCodes (content_script.js:5575:11)
    at setLng (content_script.js:6797:79)
    at I18n.changeLanguage (content_script.js:6818:7)
    at content_script.js:3320:16
```

This persists even when logged out.

### Screenshots:

![image](https://github.com/user-attachments/assets/f2ad30b0-441b-4c22-bafe-b8bba90df199)
![image](https://github.com/user-attachments/assets/ac3f2767-520e-45f7-9210-c216abae9bc0)
![image](https://github.com/user-attachments/assets/4720e2f7-d6f9-4b96-bfcb-60bfdd287a65)

### To Reproduce:
Simply run ```npm start```

### Desktop:

 - OS: Windows 10
 - Browser: Google Chrome

## Additional Context:

- This, at the very least, does not seem to interfere with any other expected behavior.
- It's worth noting that there is a Chrome extension error directly preceding the loop.
- It's possible this is isolated to my own environment. If the issue can't be replicated, please inform.

**Comment by joshua-cornett** [comment]
Closing, as the issue is no longer occurring.

**Comment by joshua-cornett** [comment]
Meant to close as not planned, as I am closing it because it is no longer replicable (i.e. no longer occurring).
